upstreams:
  groups:
    default:
      - https://cloudflare-dns.com/dns-query
      - https://dns10.quad9.net/dns-query
      - https://unfiltered.adguard-dns.com/dns-query
  strategy: parallel_best # Default

minTlsServeVersion: 1.2
connectIPVersion: dual # Default

bootstrapDns:
  - tcp+udp:1.1.1.1
  - https://1.1.1.1/dns-query
  - upstream: https://dns.digitale-gesellschaft.ch/dns-query
    ips:
      - 185.95.218.42

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

  clientGroupsBlock:
    default:
      - ads

ports:
  dns:
    - "[::1]:53"
    - "127.0.0.1:53"

log:
  level: debug
  format: text # json
  timestamp: true
  privacy: false
